function NN = train(INPUT_IMAGES, TARGET_IMAGES)
	[H, SIZE] = size(INPUT_IMAGES);
	for i = 1:SIZE
		[X Y] = tilize(INPUT_IMAGES(i), TARGET_IMAGES(i));
		TRAIN_INPUT = [TRAIN_INPUT X];
		TRAIN_TARGET = [TRAIN_TARGET Y];
	end
	NN = newrb(TRAIN_INPUT, TRAIN_TARGET);
end